version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - minha-rede

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: meu-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: senha_admin
    ports:
      - "5050:80"
    networks:
      - minha-rede
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  minha-rede: